'use strict';

const fs = require('fs');
const path = require('path');
const B = require('./book-status');

const DB_FILE = 'raff-library.json';
const SCHEMA_VERSION = 8;
const MAX_ACTIVITY = 1000;
const TRASH_RETENTION_DAYS = 30;

// Default loan period; the auto due date is this many days after borrowing.
const DEFAULT_LOAN_DAYS = 30;

const COPY_CONDITIONS = ['جيدة', 'مقبولة', 'تالفة', 'مفقودة'];

function nowIso() {
  return new Date().toISOString();
}

function genId() {
  return 'b_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 8);
}

function genLoanId() {
  return 'l_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 8);
}

/** Prices are stored as a non-negative number, or null when unspecified. */
function sanitizePrice(value) {
  if (value === '' || value === null || value === undefined) return null;
  const n = Number(value);
  if (!isFinite(n) || n < 0) return null;
  return Math.round(n * 100) / 100;
}

function escapeXml(str) {
  return (str ?? '').toString()
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Normalizes a keywords value to a clean array of unique non-empty tags. */
function sanitizeKeywords(value) {
  let arr = [];
  if (Array.isArray(value)) arr = value;
  else if (typeof value === 'string') arr = value.split(/[،,]/);
  const out = [];
  const seen = new Set();
  for (const raw of arr) {
    const t = (raw || '').toString().trim();
    if (t && !seen.has(t)) { seen.add(t); out.push(t); }
  }
  return out;
}

function sanitizeCondition(value) {
  const v = (value || '').toString().trim();
  return COPY_CONDITIONS.includes(v) ? v : 'جيدة';
}

/**
 * Cleans only formatting noise that cannot be a meaningful part of a reference
 * number: surrounding whitespace, invisible direction/zero-width characters,
 * Unicode dash variants, and spaces around separators. It deliberately keeps
 * every digit. Therefore raf-0001 and raf-1001 remain different identifiers.
 */
function cleanReferenceText(value) {
  return (value ?? '').toString()
    .normalize('NFKC')
    .replace(/[​-‏‪-‮⁠-⁩﻿]/g, '')
    .replace(/[‐-―−﹘﹣－]/g, '-')
    .replace(/[٠-٩]/g, (d) => String(d.charCodeAt(0) - 0x0660))
    .replace(/[۰-۹]/g, (d) => String(d.charCodeAt(0) - 0x06F0))
    .trim()
    .replace(/\s*-\s*/g, '-')
    .replace(/\s+/g, ' ');
}

/**
 * Canonical storage format for references generated by Raff. Custom schemes
 * are preserved (apart from harmless cleanup), while RAF-1 becomes raf-0001.
 */
function normalizeReferenceForStorage(value) {
  const cleaned = cleanReferenceText(value);
  const m = /^raf-(\d+)$/i.exec(cleaned);
  if (!m) return cleaned;
  const digits = m[1].replace(/^0+(?=\d)/, '');
  return 'raf-' + digits.padStart(4, '0');
}

/**
 * Stable identity used everywhere uniqueness is checked. The comparison is on
 * the complete cleaned reference, never on a suffix or a partial match.
 * Formatting-equivalent canonical references (raf-1 / RAF – 0001) collide,
 * while raf-0001 / raf-1001 do not.
 */
function referenceIdentity(value) {
  const cleaned = cleanReferenceText(value);
  if (!cleaned) return '';
  const m = /^raf-(\d+)$/i.exec(cleaned);
  if (m) {
    const digits = m[1].replace(/^0+(?=\d)/, '');
    return 'raff:' + digits;
  }
  return 'custom:' + cleaned.toLocaleLowerCase('en-US');
}

function normalizeTextForDuplicateHint(value) {
  return (value ?? '').toString()
    .normalize('NFKC')
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/[أإآ]/g, 'ا')
    .replace(/ى/g, 'ي')
    .toLocaleLowerCase('ar');
}

/** The inventory fields shared by addBook and updateBook. */
function normalizeInventoryFields(book) {
  return {
    series: (book.series || '').trim(),                 // اسم السلسلة
    seriesOrder: (book.seriesOrder || '').toString().trim(), // رقم المجلد/الترتيب داخل السلسلة
    keywords: sanitizeKeywords(book.keywords),          // كلمات مفتاحية
    condition: sanitizeCondition(book.condition),       // حالة النسخة
    acquisition: (book.acquisition || '').trim(),       // جهة الاقتناء
    shelf: (book.shelf || '').trim(),                   // الرف
  };
}

function makeRecordDefaults() {
  return { series: '', seriesOrder: '', keywords: [], condition: 'جيدة', acquisition: '', shelf: '' };
}

function emptyDb() {
  return {
    schemaVersion: SCHEMA_VERSION,
    createdAt: nowIso(),
    nextRefSeq: 1,
    books: [],
    trash: [],
    activity: [],
    lastDailyBackupAt: null,
    settings: defaultSettings(),
  };
}

/** Institution branding and label-printing preferences. */
function defaultSettings() {
  return {
    institutionName: '',   // اسم المكتبة/المؤسسة على الملصقات
    logo: '',              // شعار كـ data URL (base64) — يبقى محلياً
    labelColumns: 4,       // عدد الأعمدة في ورقة A4
    labelSize: 'small',    // small | medium — حجم الملصق للصق خلف الكتاب
    labelShowPrice: true,
    labelShowShelf: true,
    labelShowMicrotext: true, // معلومات دقيقة شبه خفية
    loanDurationDays: 30,      // مدة الإعارة الافتراضية بالأيام
    scannerGapMs: 35,          // حساسية قارئ الباركود
    scannerTerminator: 'Enter',
    savedFilters: [],          // فلاتر البحث المحفوظة
  };
}

/**
 * A minimal, dependency-free JSON datastore. Chosen over a native SQLite
 * binding so the packaged app never has to rebuild native modules per
 * platform/Electron ABI — a common source of broken installers.
 */
class Store {
  constructor(userDataDir) {
    this.filePath = path.join(userDataDir, DB_FILE);
    this.recoveryNotice = null;
    this._load();
    this._rebuildIndexes();
    this._pruneTrash();
    this.ensureDailyBackup();
  }

  _load() {
    try {
      if (!fs.existsSync(this.filePath)) {
        this.db = emptyDb();
        this._save();
        return;
      }
      const raw = fs.readFileSync(this.filePath, 'utf-8');
      this.db = JSON.parse(raw);
      if (!this.db.books) this.db.books = [];
      if (!this.db.nextRefSeq) {
        // Upgrading an older database: start the counter past any existing
        // numeric suffixes so newly generated numbers can't collide.
        let maxSeq = 0;
        for (const b of this.db.books) {
          const seq = this._canonicalRefSeq(b.referenceNumber);
          if (seq !== null) maxSeq = Math.max(maxSeq, seq);
        }
        this.db.nextRefSeq = maxSeq + 1;
      }
      this._migrate();
    } catch (err) {
      // Corrupt file safety net: preserve the unreadable file and expose a
      // recovery notice so the renderer never mistakes a fresh database for
      // mysteriously-lost data.
      let corruptPath = null;
      try {
        if (fs.existsSync(this.filePath)) {
          corruptPath = this.filePath + '.corrupt-' + Date.now();
          fs.copyFileSync(this.filePath, corruptPath);
        }
      } catch (_) {}
      this.db = emptyDb();
      this._save();
      this.recoveryNotice = {
        reason: 'corrupt-database',
        message: err && err.message ? err.message : 'تعذر قراءة قاعدة البيانات',
        corruptPath,
      };
    }
  }

  _save() {
    fs.mkdirSync(path.dirname(this.filePath), { recursive: true });
    const tmp = this.filePath + '.tmp';
    // Internal store is written compactly (no pretty-print) so it stays small
    // and fast to read/write even with thousands of records. The human-readable
    // formatting is reserved for exportJson. Written to a temp file then renamed
    // so an interrupted write can never corrupt the live database.
    const fd = fs.openSync(tmp, 'w');
    try {
      fs.writeFileSync(fd, JSON.stringify(this.db), 'utf-8');
      try { fs.fsyncSync(fd); } catch (_) {}
    } finally {
      fs.closeSync(fd);
    }
    fs.renameSync(tmp, this.filePath);
    try {
      const dirFd = fs.openSync(path.dirname(this.filePath), 'r');
      try { fs.fsyncSync(dirFd); } catch (_) {}
      fs.closeSync(dirFd);
    } catch (_) {}
  }

  /** Writes a timestamped copy of the current database into a backups folder. */
  createBackup(reason = 'manual') {
    const dir = path.join(path.dirname(this.filePath), 'backups');
    fs.mkdirSync(dir, { recursive: true });
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const file = path.join(dir, `raff-backup-${stamp}-${reason}.json`);
    fs.writeFileSync(file, JSON.stringify(this.db, null, 2), 'utf-8');
    this._pruneBackupsSmart(dir);
    return file;
  }

  /** Keeps only the newest `keep` backups so the folder can't grow forever. */
  _pruneBackups(dir, keep) {
    try {
      const files = fs.readdirSync(dir)
        .filter((f) => f.startsWith('raff-backup-') && f.endsWith('.json'))
        .map((f) => ({ f, t: fs.statSync(path.join(dir, f)).mtimeMs }))
        .sort((a, b) => b.t - a.t);
      for (const { f } of files.slice(keep)) {
        try { fs.unlinkSync(path.join(dir, f)); } catch (_) { /* ignore */ }
      }
    } catch (_) { /* ignore */ }
  }

  _pruneBackupsSmart(dir) {
    try {
      const files = fs.readdirSync(dir)
        .filter((f) => f.startsWith('raff-backup-') && f.endsWith('.json'))
        .map((f) => ({ f, t: fs.statSync(path.join(dir, f)).mtimeMs, daily: f.endsWith('-daily.json') }))
        .sort((a, b) => b.t - a.t);

      const keep = new Set();
      const dailyDays = new Set();
      const weekly = new Set();
      let weeklyCount = 0;
      let specialCount = 0;
      for (const item of files) {
        const d = new Date(item.t);
        if (item.daily) {
          const day = d.toISOString().slice(0, 10);
          if (dailyDays.size < 7 && !dailyDays.has(day)) {
            dailyDays.add(day); keep.add(item.f); continue;
          }
          const oneJan = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
          const weekNo = Math.ceil((((d - oneJan) / 86400000) + oneJan.getUTCDay() + 1) / 7);
          const weekKey = `${d.getUTCFullYear()}-${weekNo}`;
          if (weeklyCount < 4 && !weekly.has(weekKey)) {
            weekly.add(weekKey); weeklyCount += 1; keep.add(item.f);
          }
        } else if (specialCount < 20) {
          specialCount += 1; keep.add(item.f);
        }
      }
      for (const item of files) if (!keep.has(item.f)) {
        try { fs.unlinkSync(path.join(dir, item.f)); } catch (_) {}
      }
    } catch (_) {}
  }

  listBackups() {
    const dir = path.join(path.dirname(this.filePath), 'backups');
    try {
      return fs.readdirSync(dir)
        .filter((f) => f.startsWith('raff-backup-') && f.endsWith('.json'))
        .map((f) => {
          const filePath = path.join(dir, f);
          const st = fs.statSync(filePath);
          let books = null;
          try {
            const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            books = Array.isArray(parsed.books) ? parsed.books.length : null;
          } catch (_) {}
          return { name: f, filePath, createdAt: st.mtime.toISOString(), size: st.size, books };
        })
        .sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt));
    } catch (_) { return []; }
  }

  getRecoveryState() {
    return { notice: this.recoveryNotice, backups: this.listBackups().slice(0, 12) };
  }

  ensureDailyBackup() {
    const today = new Date().toISOString().slice(0, 10);
    const last = (this.db.lastDailyBackupAt || '').slice(0, 10);
    if (last === today || !this.db.books.length) return null;
    try {
      const file = this.createBackup('daily');
      this.db.lastDailyBackupAt = nowIso();
      this._save();
      return file;
    } catch (_) { return null; }
  }

  dataDir() { return path.dirname(this.filePath); }

  /**
   * v1 stored a single `status` string plus one `borrowerName`. v2 stores a
   * loan ledger and derives status from it. Convert in place, once, and keep
   * the old borrower as an open loan dated to the record's creation.
   */
  _migrate() {
    let changed = false;
    const from = this.db.schemaVersion || 1;
    if (from >= SCHEMA_VERSION) return;

    for (const book of this.db.books) {
      // v1 -> v2: single status/borrower becomes a loan ledger.
      if (!Array.isArray(book.loans)) book.loans = [];
      const wasBorrowed = book.status === 'معار';
      if (wasBorrowed && book.loans.length === 0) {
        book.loans.push({
          id: genLoanId(),
          borrowerName: (book.borrowerName || 'غير معروف').trim(),
          borrowedAt: book.updatedAt || book.createdAt || nowIso(),
          returnedAt: null,
        });
      }
      delete book.status;
      delete book.borrowerName;

      // v2 -> v3: price and volumes fields.
      if (book.volumes === undefined) { book.volumes = 1; changed = true; }
      if (book.price === undefined) { book.price = null; changed = true; }
      // Loans predating volume-level lending are whole-copy loans.
      for (const loan of book.loans || []) {
        if (loan.type === undefined) { loan.type = 'full'; loan.volume = null; changed = true; }
        // v4 -> v5: a partial loan can contain one or several volume numbers.
        if (loan.type === 'volume' || loan.volume != null || Array.isArray(loan.volumes)) {
          const raw = Array.isArray(loan.volumes) ? loan.volumes : (loan.volume != null ? [loan.volume] : []);
          const volumes = [...new Set(raw.map((v) => Math.floor(Number(v))).filter((v) => v > 0))].sort((a, b) => a - b);
          if (JSON.stringify(loan.volumes || []) !== JSON.stringify(volumes)) { loan.volumes = volumes; changed = true; }
          const legacyVolume = volumes.length === 1 ? volumes[0] : null;
          if (loan.volume !== legacyVolume) { loan.volume = legacyVolume; changed = true; }
          if (volumes.length > 0 && loan.type !== 'volume') { loan.type = 'volume'; changed = true; }
          if (volumes.length === 0 && loan.type !== 'full') { loan.type = 'full'; changed = true; }
        } else {
          if (!Array.isArray(loan.volumes) || loan.volumes.length) { loan.volumes = []; changed = true; }
          if (loan.volume !== null) { loan.volume = null; changed = true; }
        }
        // v3 -> v4: loans gain a due date, contact, and per-loan note.
        if (loan.dueAt === undefined) {
          const start = Date.parse(loan.borrowedAt) || Date.now();
          loan.dueAt = new Date(start + DEFAULT_LOAN_DAYS * 86400000).toISOString();
          changed = true;
        }
        if (loan.contact === undefined) { loan.contact = ''; changed = true; }
        if (loan.note === undefined) { loan.note = ''; changed = true; }
        // v5 -> v6: each volume can be returned independently.
        if (!loan.volumeReturns || typeof loan.volumeReturns !== 'object' || Array.isArray(loan.volumeReturns)) {
          loan.volumeReturns = {};
          changed = true;
        }
      }

      // v3 -> v4: new inventory fields.
      const defs = makeRecordDefaults();
      for (const k of Object.keys(defs)) {
        if (book[k] === undefined) { book[k] = defs[k]; changed = true; }
      }
      if (!Array.isArray(book.keywords)) { book.keywords = sanitizeKeywords(book.keywords); changed = true; }
    }
    if (!Array.isArray(this.db.trash)) { this.db.trash = []; changed = true; }
    if (!Array.isArray(this.db.activity)) { this.db.activity = []; changed = true; }
    if (this.db.lastDailyBackupAt === undefined) { this.db.lastDailyBackupAt = null; changed = true; }

    // Ensure the settings object exists and has every key (older DBs lack it).
    if (!this.db.settings || typeof this.db.settings !== 'object') this.db.settings = defaultSettings();
    else {
      const defs = defaultSettings();
      for (const k of Object.keys(defs)) {
        if (this.db.settings[k] === undefined) this.db.settings[k] = defs[k];
      }
    }
    this.db.schemaVersion = SCHEMA_VERSION;
    this._save();
    void changed;
  }

  getSettings() {
    if (!this.db.settings) this.db.settings = defaultSettings();
    return { ...this.db.settings };
  }

  /** Updates institution/label settings. Logo is validated to be a data URL. */
  updateSettings(patch) {
    const cur = this.getSettings();
    const next = { ...cur };
    if (patch.institutionName !== undefined) next.institutionName = (patch.institutionName || '').toString().slice(0, 120).trim();
    if (patch.logo !== undefined) {
      const logo = (patch.logo || '').toString();
      // Only accept an image data URL, or empty to clear it.
      next.logo = (logo === '' || /^data:image\/(png|jpe?g|gif|webp|svg\+xml);base64,/.test(logo)) ? logo : cur.logo;
    }
    if (patch.labelColumns !== undefined) {
      const n = Math.floor(Number(patch.labelColumns));
      next.labelColumns = (n >= 1 && n <= 5) ? n : cur.labelColumns;
    }
    if (patch.labelSize !== undefined) {
      next.labelSize = ['small', 'medium'].includes(patch.labelSize) ? patch.labelSize : cur.labelSize;
    }
    if (patch.loanDurationDays !== undefined) {
      const n = Math.floor(Number(patch.loanDurationDays));
      next.loanDurationDays = (n >= 1 && n <= 3650) ? n : cur.loanDurationDays;
    }
    if (patch.scannerGapMs !== undefined) {
      const n = Math.floor(Number(patch.scannerGapMs));
      next.scannerGapMs = (n >= 15 && n <= 250) ? n : cur.scannerGapMs;
    }
    if (patch.scannerTerminator !== undefined) {
      next.scannerTerminator = ['Enter', 'Tab'].includes(patch.scannerTerminator) ? patch.scannerTerminator : cur.scannerTerminator;
    }
    if (patch.savedFilters !== undefined && Array.isArray(patch.savedFilters)) {
      next.savedFilters = patch.savedFilters.slice(0, 20).map((f) => ({
        id: (f.id || genId()).toString().slice(0, 80),
        name: (f.name || '').toString().trim().slice(0, 80),
        query: (f.query || '').toString().slice(0, 200),
        field: (f.field || 'all').toString().slice(0, 30),
        status: (f.status || 'all').toString().slice(0, 30),
        sort: (f.sort || 'newest').toString().slice(0, 30),
      })).filter((f) => f.name);
    }
    for (const k of ['labelShowPrice', 'labelShowShelf', 'labelShowMicrotext']) {
      if (patch[k] !== undefined) next[k] = !!patch[k];
    }
    this.db.settings = next;
    this._logActivity('settings-updated', 'تم تحديث إعدادات البرنامج');
    this._save();
    return { ...next };
  }

  /** Resolves a reference-number range (e.g. raf-0001..raf-0100) to books. */
  booksInReferenceRange(fromRef, toRef) {
    const num = (r) => {
      const m = /(\d+)\s*$/.exec((r || '').trim());
      return m ? parseInt(m[1], 10) : null;
    };
    const a = num(fromRef), b = num(toRef);
    if (a === null || b === null) return [];
    const lo = Math.min(a, b), hi = Math.max(a, b);
    return this.db.books
      .filter((bk) => { const n = num(bk.referenceNumber); return n !== null && n >= lo && n <= hi; })
      .sort((x, y) => num(x.referenceNumber) - num(y.referenceNumber));
  }

  getAll() {
    return this.db.books;
  }

  getMeta() {
    const authors = new Set();
    const publishers = new Set();
    const categories = new Set();
    const borrowers = new Set();
    const years = new Set();
    const series = new Set();
    const shelves = new Set();
    const keywords = new Set();
    for (const b of this.db.books) {
      if (b.author) authors.add(b.author.trim());
      if (b.publisher) publishers.add(b.publisher.trim());
      if (b.category) categories.add(b.category.trim());
      if (b.publishYear) years.add(b.publishYear.trim());
      if (b.series) series.add(b.series.trim());
      if (b.shelf) shelves.add(b.shelf.trim());
      for (const k of b.keywords || []) if (k) keywords.add(k.trim());
      for (const loan of b.loans || []) {
        if (loan.borrowerName) borrowers.add(loan.borrowerName.trim());
      }
    }
    const arSort = (a, c) => a.localeCompare(c, 'ar');
    const borrowerProfiles = this.getBorrowersDirectory().map((p) => ({ name: p.name, contact: p.contact, contacts: p.contacts, currentCount: p.currentCount, overdueCount: p.overdueCount, totalLoans: p.totalLoans, lastLoanAt: p.lastLoanAt }));
    return {
      authors: [...authors].sort(arSort),
      publishers: [...publishers].sort(arSort),
      categories: [...categories].sort(arSort),
      borrowers: [...borrowers].sort(arSort),
      borrowerProfiles,
      years: [...years].sort(arSort),
      series: [...series].sort(arSort),
      shelves: [...shelves].sort(arSort),
      keywords: [...keywords].sort(arSort),
      filePath: this.filePath,
    };
  }

  // A reference counts toward the auto-sequence only if its complete cleaned
  // value matches Raff's canonical format. No suffix-only comparison is ever
  // used: raf-0001 and raf-1001 are intentionally different sequence values.
  _canonicalRefSeq(ref) {
    const m = /^raf-(\d+)$/i.exec(cleanReferenceText(ref));
    if (!m) return null;
    const n = Number(m[1]);
    return Number.isSafeInteger(n) && n > 0 ? n : null;
  }

  _referenceIdentity(ref) {
    return referenceIdentity(ref);
  }

  _normalizeReference(ref) {
    return normalizeReferenceForStorage(ref);
  }

  _rebuildIndexes() {
    this._refIdentityIndex = new Map();
    this._usedSeqIndex = new Set();
    for (const b of this.db.books || []) {
      const key = this._referenceIdentity(b.referenceNumber);
      if (key && !this._refIdentityIndex.has(key)) this._refIdentityIndex.set(key, b);
      const seq = this._canonicalRefSeq(b.referenceNumber);
      if (seq !== null) this._usedSeqIndex.add(seq);
    }
    let next = Math.max(1, Number(this.db.nextRefSeq) || 1);
    while (this._usedSeqIndex.has(next)) next += 1;
    this.db.nextRefSeq = next;
  }

  _indexBook(book) {
    const key = this._referenceIdentity(book.referenceNumber);
    if (key) this._refIdentityIndex.set(key, book);
    const seq = this._canonicalRefSeq(book.referenceNumber);
    if (seq !== null) this._usedSeqIndex.add(seq);
    while (this._usedSeqIndex.has(this.db.nextRefSeq)) this.db.nextRefSeq += 1;
  }

  _unindexBook(book) {
    const key = this._referenceIdentity(book.referenceNumber);
    if (key && this._refIdentityIndex.get(key)?.id === book.id) this._refIdentityIndex.delete(key);
    const seq = this._canonicalRefSeq(book.referenceNumber);
    if (seq !== null) this._usedSeqIndex.delete(seq);
    if (seq !== null && seq < this.db.nextRefSeq) this.db.nextRefSeq = seq;
  }

  _findReferenceClash(ref, excludeId = null) {
    const wanted = this._referenceIdentity(ref);
    if (!wanted) return null;
    const indexed = this._refIdentityIndex.get(wanted) || null;
    if (indexed && indexed.id !== excludeId) return indexed;
    return null;
  }

  /** The set of canonical raf-NNNN sequence numbers currently in use. */
  _usedCanonicalSeqs() {
    return new Set(this._usedSeqIndex);
  }

  /** Lowest free canonical sequence number, starting from the maintained hint. */
  _lowestFreeSeq() {
    let seq = Math.max(1, Number(this.db.nextRefSeq) || 1);
    while (this._usedSeqIndex.has(seq)) seq += 1;
    this.db.nextRefSeq = seq;
    return seq;
  }

  _nextReferenceNumber() {
    const seq = this._lowestFreeSeq();
    return 'raf-' + String(seq).padStart(4, '0');
  }

  /** Returns the next reference without reserving it. */
  peekNextReferenceNumber() {
    return 'raf-' + String(this._lowestFreeSeq()).padStart(4, '0');
  }

  addBook(book, { keepReferenceNumber = false, defer = false } = {}) {
    const requested = this._normalizeReference(book.referenceNumber || '');
    let referenceNumber;
    if (requested) {
      // Every entry path — manual entry, edit, and import — uses the same full
      // reference identity. This catches harmless formatting variants without
      // ever confusing different numbers such as raf-0001 and raf-1001.
      const clash = this._findReferenceClash(requested);
      if (clash) {
        return {
          ok: false,
          error: 'الرقم المرجعي مستخدم بالفعل',
          clash: { id: clash.id, title: clash.title, referenceNumber: clash.referenceNumber },
        };
      }
      referenceNumber = requested;
    } else {
      referenceNumber = this._nextReferenceNumber();
    }
    void keepReferenceNumber;

    const record = {
      id: genId(),
      title: (book.title || '').trim(),
      author: (book.author || '').trim(),
      publisher: (book.publisher || '').trim(),
      referenceNumber,
      category: (book.category || '').trim(),
      edition: (book.edition || '').trim(),
      publishYear: (book.publishYear || '').toString().trim(),
      copiesTotal: Number(book.copiesTotal) > 0 ? Number(book.copiesTotal) : 1,
      volumes: Number(book.volumes) > 0 ? Math.floor(Number(book.volumes)) : 1,
      price: sanitizePrice(book.price),
      ...normalizeInventoryFields(book),
      // Status is derived from this ledger; it is never stored.
      loans: Array.isArray(book.loans) ? book.loans : [],
      notes: (book.notes || '').trim(),
      language: (book.language || 'العربية').trim(),
      createdAt: nowIso(),
      updatedAt: nowIso(),
    };
    this.db.books.unshift(record);
    this._indexBook(record);
    this._logActivity('book-added', `أُضيف كتاب «${record.title || 'بدون عنوان'}»`, { bookId: record.id, referenceNumber: record.referenceNumber });
    // Bulk paths (import) defer the write; persisting the whole file once per
    // inserted book turns an import of N books into O(N^2) disk work.
    if (!defer) this._save();
    return record;
  }

  updateBook(id, patch) {
    const idx = this.db.books.findIndex((b) => b.id === id);
    if (idx === -1) return null;
    const current = this.db.books[idx];

    const safePatch = { ...patch };
    // The ledger is only ever changed through borrowCopy/returnLoan.
    delete safePatch.loans;
    delete safePatch.id;
    delete safePatch.status;
    delete safePatch.borrowerName;
    // Reference-number changes go through setReferenceNumber (uniqueness check).
    delete safePatch.referenceNumber;

    if (safePatch.copiesTotal !== undefined) {
      const requested = Number(safePatch.copiesTotal);
      // The floor is the highest number of copies any single volume has out
      // (full-copy loans count against every volume), so we never record fewer
      // copies than are physically on loan for some volume.
      let busiest = B.borrowedFullCopies(current);
      const vols = B.totalVolumes(current);
      for (let v = 1; v <= vols; v++) {
        const out = B.borrowedOfVolume(current, v);
        if (out > busiest) busiest = out;
      }
      safePatch.copiesTotal = Math.max(busiest || 1, requested > 0 ? requested : 1);
    }
    if (safePatch.volumes !== undefined) {
      let requested = Number(safePatch.volumes) > 0 ? Math.floor(Number(safePatch.volumes)) : 1;
      // Don't drop the volume count below the highest volume number currently
      // out on loan, or that loan would reference a volume that no longer exists.
      let maxVolOut = 1;
      for (const l of B.activeLoans(current)) {
        for (const volume of B.loanVolumes(l)) {
          if (volume > maxVolOut) maxVolOut = volume;
        }
      }
      safePatch.volumes = Math.max(requested, maxVolOut);
    }
    if (safePatch.price !== undefined) {
      safePatch.price = sanitizePrice(safePatch.price);
    }
    if (safePatch.keywords !== undefined) safePatch.keywords = sanitizeKeywords(safePatch.keywords);
    if (safePatch.condition !== undefined) safePatch.condition = sanitizeCondition(safePatch.condition);
    for (const f of ['series', 'seriesOrder', 'acquisition', 'shelf']) {
      if (safePatch[f] !== undefined) safePatch[f] = (safePatch[f] || '').toString().trim();
    }

    const updated = { ...current, ...safePatch, id: current.id, loans: current.loans, updatedAt: nowIso() };
    this.db.books[idx] = updated;
    this._logActivity('book-updated', `عُدّلت بيانات «${updated.title || 'بدون عنوان'}»`, { bookId: updated.id });
    this._save();
    return updated;
  }

  /**
   * Reference numbers must stay unique. Returns { ok, error?, book? } so the
   * UI can refuse a clash rather than silently create a duplicate.
   */
  setReferenceNumber(id, referenceNumber) {
    const ref = this._normalizeReference(referenceNumber || '');
    if (!ref) return { ok: false, error: 'الرقم المرجعي لا يمكن أن يكون فارغاً' };
    const clash = this._findReferenceClash(ref, id);
    if (clash) {
      return {
        ok: false,
        error: `هذا الرقم المرجعي مستخدم في «${clash.title || 'كتاب آخر'}»`,
        clash: { id: clash.id, title: clash.title, referenceNumber: clash.referenceNumber },
      };
    }
    const book = this.db.books.find((b) => b.id === id);
    if (!book) return { ok: false, error: 'الكتاب غير موجود' };
    this._unindexBook(book);
    const before = book.referenceNumber;
    book.referenceNumber = ref;
    book.updatedAt = nowIso();
    this._indexBook(book);
    this._logActivity('reference-updated', `تغيّر الرقم المرجعي لكتاب «${book.title || 'بدون عنوان'}»`, { bookId: book.id, before, after: ref });
    this._save();
    return { ok: true, book };
  }

  /**
   * Lends either a whole copy (all volumes) or one/more selected volumes.
   * payload: { borrowerName, borrowedAt, scope: 'full'|'volume', volumes?, volume? }
   * `volume` remains accepted for compatibility with older renderer builds.
   * Returns { ok, error?, book? }.
   */
  borrowCopy(bookId, payload = {}) {
    const book = this.db.books.find((b) => b.id === bookId);
    if (!book) return { ok: false, error: 'الكتاب غير موجود' };

    const name = (payload.borrowerName || '').trim();
    if (!name) return { ok: false, error: 'اسم المستعير مطلوب' };

    const multi = B.isMultiVolume(book);
    const scope = (multi && payload.scope === 'volume') ? 'volume' : 'full';

    let volumes = [];
    if (scope === 'volume') {
      const rawVolumes = Array.isArray(payload.volumes) ? payload.volumes : [payload.volume];
      volumes = [...new Set(rawVolumes
        .map((v) => Math.floor(Number(v)))
        .filter((v) => Number.isFinite(v)))]
        .sort((a, b) => a - b);

      const totalVolumes = B.totalVolumes(book);
      if (volumes.length === 0) return { ok: false, error: 'اختر جزءًا واحدًا على الأقل' };
      const invalid = volumes.filter((v) => !(v >= 1 && v <= totalVolumes));
      if (invalid.length) return { ok: false, error: `أرقام الأجزاء يجب أن تكون بين 1 و ${totalVolumes}` };

      const unavailable = volumes.filter((v) => !B.canBorrowVolume(book, v));
      if (unavailable.length) {
        const label = unavailable.length === 1 ? `الجزء ${unavailable[0]}` : `الأجزاء ${unavailable.join('، ')}`;
        return { ok: false, error: `لا توجد نسخة متاحة من ${label}` };
      }
    } else if (!B.canBorrow(book)) {
      return { ok: false, error: 'لا توجد نسخة كاملة متاحة للإعارة' };
    }

    const when = payload.borrowedAt ? new Date(payload.borrowedAt) : new Date();
    if (isNaN(when.getTime())) return { ok: false, error: 'تاريخ الإعارة غير صالح' };
    if (when.getTime() > Date.now() + 86400000) return { ok: false, error: 'لا يمكن أن يكون تاريخ الإعارة في المستقبل' };

    // Due date defaults to the library's configured loan period after
    // borrowing (30 days out of the box), but can be set explicitly.
    let due;
    if (payload.dueAt) {
      due = new Date(payload.dueAt);
      if (isNaN(due.getTime())) return { ok: false, error: 'تاريخ الإرجاع غير صالح' };
      if (due.getTime() < when.getTime()) return { ok: false, error: 'تاريخ الإرجاع أسبق من تاريخ الإعارة' };
    } else {
      const days = this.getSettings().loanDurationDays || DEFAULT_LOAN_DAYS;
      due = new Date(when.getTime() + days * 86400000);
    }

    book.loans.push({
      id: genLoanId(),
      borrowerName: name,
      type: scope === 'volume' ? B.LOAN_VOLUME : B.LOAN_FULL,
      volumes: scope === 'volume' ? volumes : [],
      // Keep the legacy field only when exactly one part was selected.
      volume: scope === 'volume' && volumes.length === 1 ? volumes[0] : null,
      borrowedAt: when.toISOString(),
      dueAt: due.toISOString(),
      contact: (payload.contact || '').trim(),
      note: (payload.note || '').trim(),
      volumeReturns: {},
      returnedAt: null,
    });
    book.updatedAt = nowIso();
    this._logActivity('loan-opened', `أُعير «${book.title || 'بدون عنوان'}» إلى ${name}`, { bookId: book.id, borrowerName: name });
    this._save();
    return { ok: true, book };
  }

  /**
   * Returns all parts that are still outstanding on one loan. Kept as the
   * backwards-compatible whole-loan action used by older renderer builds.
   */
  returnLoan(bookId, loanId, returnedAt) {
    return this._returnLoanParts(bookId, loanId, null, returnedAt);
  }

  /** Returns one or several selected parts while leaving the rest open. */
  returnLoanParts(bookId, loanId, volumes, returnedAt) {
    return this._returnLoanParts(bookId, loanId, volumes, returnedAt);
  }

  _returnLoanParts(bookId, loanId, volumes, returnedAt) {
    const book = this.db.books.find((b) => b.id === bookId);
    if (!book) return { ok: false, error: 'الكتاب غير موجود' };
    const loan = (book.loans || []).find((l) => l.id === loanId);
    if (!loan || !B.isLoanActive(loan, book)) {
      return { ok: false, error: 'الإعارة غير موجودة أو أُرجعت بالكامل مسبقاً' };
    }

    const when = returnedAt ? new Date(returnedAt) : new Date();
    if (isNaN(when.getTime())) return { ok: false, error: 'تاريخ الإرجاع غير صالح' };
    if (when.getTime() < Date.parse(loan.borrowedAt)) {
      return { ok: false, error: 'تاريخ الإرجاع أسبق من تاريخ الإعارة' };
    }

    const outstanding = B.outstandingLoanVolumes(loan, book);
    let selected = volumes == null ? outstanding : [...new Set((Array.isArray(volumes) ? volumes : [volumes])
      .map((v) => Math.floor(Number(v)))
      .filter((v) => Number.isFinite(v) && v > 0))].sort((a, b) => a - b);

    if (selected.length === 0) return { ok: false, error: 'اختر جزءًا واحدًا على الأقل لإرجاعه' };
    const invalid = selected.filter((v) => !outstanding.includes(v));
    if (invalid.length) {
      const label = invalid.length === 1 ? `الجزء ${invalid[0]}` : `الأجزاء ${invalid.join('، ')}`;
      return { ok: false, error: `${label} غير موجودة ضمن الأجزاء المعارة حالياً أو أُرجعت مسبقاً` };
    }

    if (!loan.volumeReturns || typeof loan.volumeReturns !== 'object' || Array.isArray(loan.volumeReturns)) {
      loan.volumeReturns = {};
    }
    const stamp = when.toISOString();
    for (const volume of selected) loan.volumeReturns[String(volume)] = stamp;

    const remaining = B.outstandingLoanVolumes(loan, book);
    if (remaining.length === 0) {
      const returnTimes = Object.values(loan.volumeReturns)
        .map((value) => Date.parse(value))
        .filter((value) => Number.isFinite(value));
      loan.returnedAt = new Date(returnTimes.length ? Math.max(...returnTimes) : when.getTime()).toISOString();
    } else {
      loan.returnedAt = null;
    }

    book.updatedAt = nowIso();
    this._logActivity('loan-returned', `سُجّل إرجاع «${book.title || 'بدون عنوان'}»`, { bookId: book.id, loanId, returnedVolumes: selected });
    this._save();
    return {
      ok: true,
      book,
      returnedVolumes: selected,
      remainingVolumes: remaining,
      completed: remaining.length === 0,
    };
  }

  removeBook(id) {
    const book = this.db.books.find((b) => b.id === id);
    if (!book) return { ok: false, error: 'الكتاب غير موجود' };
    if (B.activeLoans(book).length) {
      return { ok: false, error: 'لا يمكن حذف كتاب لديه إعارة مفتوحة. أرجع الإعارة أولاً أو أرشف الكتاب.' };
    }
    this._unindexBook(book);
    this.db.books = this.db.books.filter((b) => b.id !== id);
    const trashItem = { id: `t_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`, deletedAt: nowIso(), book };
    this.db.trash.unshift(trashItem);
    this._logActivity('book-trashed', `نُقل «${book.title || 'بدون عنوان'}» إلى سلة المحذوفات`, { bookId: book.id, trashId: trashItem.id });
    this._save();
    return { ok: true, trashId: trashItem.id };
  }

  restoreBook(bookOrTrashId) {
    let restored = null;
    let trashIndex = -1;
    if (typeof bookOrTrashId === 'string') {
      trashIndex = this.db.trash.findIndex((t) => t.id === bookOrTrashId || t.book?.id === bookOrTrashId);
      if (trashIndex >= 0) restored = { ...this.db.trash[trashIndex].book };
    } else if (bookOrTrashId && bookOrTrashId.id) {
      restored = { ...bookOrTrashId };
    }
    if (!restored || !restored.id) return null;
    const existing = this.db.books.find((b) => b.id === restored.id);
    if (existing) return existing;

    const normalized = this._normalizeReference(restored.referenceNumber || '');
    const clash = normalized ? this._findReferenceClash(normalized) : null;
    restored.referenceNumber = clash ? this._nextReferenceNumber() : (normalized || this._nextReferenceNumber());
    restored.updatedAt = nowIso();
    this.db.books.unshift(restored);
    if (trashIndex >= 0) this.db.trash.splice(trashIndex, 1);
    this._indexBook(restored);
    this._logActivity('book-restored', `استُعيد «${restored.title || 'بدون عنوان'}»`, { bookId: restored.id });
    this._save();
    return restored;
  }

  archiveBook(id, archived = true) {
    const book = this.db.books.find((b) => b.id === id);
    if (!book) return { ok: false, error: 'الكتاب غير موجود' };
    book.archivedAt = archived ? nowIso() : null;
    book.updatedAt = nowIso();
    this._logActivity(archived ? 'book-archived' : 'book-unarchived', `${archived ? 'أُرشف' : 'أُعيد'} «${book.title || 'بدون عنوان'}»`, { bookId: id });
    this._save();
    return { ok: true, book };
  }

  getTrash() {
    return (this.db.trash || []).map((t) => ({ ...t, book: { ...t.book } }));
  }

  purgeTrash() {
    const count = this.db.trash.length;
    this.db.trash = [];
    this._logActivity('trash-purged', `أُفرغت سلة المحذوفات (${count})`);
    this._save();
    return { count };
  }

  _pruneTrash() {
    if (!Array.isArray(this.db.trash)) this.db.trash = [];
    const cutoff = Date.now() - TRASH_RETENTION_DAYS * 86400000;
    const before = this.db.trash.length;
    this.db.trash = this.db.trash.filter((t) => (Date.parse(t.deletedAt) || Date.now()) >= cutoff);
    if (before !== this.db.trash.length) this._save();
  }

  _logActivity(type, message, details = {}) {
    if (!Array.isArray(this.db.activity)) this.db.activity = [];
    this.db.activity.unshift({ id: `a_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`, type, message, details, createdAt: nowIso() });
    if (this.db.activity.length > MAX_ACTIVITY) this.db.activity.length = MAX_ACTIVITY;
  }

  getActivity(limit = 200) {
    return (this.db.activity || []).slice(0, Math.max(1, Math.min(1000, Number(limit) || 200)));
  }

  findPossibleDuplicates(book, excludeId = null) {
    const title = normalizeTextForDuplicateHint(book && book.title);
    const author = normalizeTextForDuplicateHint(book && book.author);
    const publisher = normalizeTextForDuplicateHint(book && book.publisher);
    const year = normalizeTextForDuplicateHint(book && book.publishYear);
    if (!title) return [];
    return this.db.books.filter((b) => {
      if (b.id === excludeId) return false;
      if (normalizeTextForDuplicateHint(b.title) !== title) return false;
      const sameAuthor = author && normalizeTextForDuplicateHint(b.author) === author;
      const samePublisher = publisher && normalizeTextForDuplicateHint(b.publisher) === publisher;
      const sameYear = year && normalizeTextForDuplicateHint(b.publishYear) === year;
      return sameAuthor || (samePublisher && sameYear);
    }).slice(0, 8).map((b) => ({ id: b.id, title: b.title, author: b.author, publisher: b.publisher, publishYear: b.publishYear, referenceNumber: b.referenceNumber }));
  }

  bulkUpdate(ids, patch = {}) {
    const wanted = new Set(Array.isArray(ids) ? ids : []);
    let updated = 0;
    for (const book of this.db.books) {
      if (!wanted.has(book.id)) continue;
      const next = {};
      if (patch.shelf !== undefined) next.shelf = (patch.shelf || '').toString().trim();
      if (patch.category !== undefined) next.category = (patch.category || '').toString().trim();
      if (patch.addKeyword) next.keywords = sanitizeKeywords([...(book.keywords || []), patch.addKeyword]);
      Object.assign(book, next, { updatedAt: nowIso() });
      updated += 1;
    }
    if (updated) {
      this._logActivity('books-bulk-updated', `عُدّلت ${updated} سجلات دفعة واحدة`, { count: updated });
      this._save();
    }
    return { updated };
  }

  getStats() {
    const books = this.db.books;
    const byCategory = {};
    const byPublisher = {};
    let totalCopies = 0;
    let borrowedCopies = 0;
    let fullyBorrowed = 0;
    let partiallyBorrowed = 0;
    let activeBorrowers = new Set();
    let totalValue = 0;
    let pricedCopies = 0;
    let overdueLoans = 0;
    let dueSoonLoans = 0;
    let pricedTitles = 0;
    let multiVolumeTitles = 0;
    let completeRecords = 0;
    let topPriced = null;
    const now = Date.now();

    // Fields that make an inventory record "complete".
    const completenessFields = ['title', 'author', 'publisher', 'referenceNumber', 'category', 'publishYear'];

    for (const b of books) {
      const cat = b.category || 'غير مصنف';
      byCategory[cat] = (byCategory[cat] || 0) + 1;
      const pub = b.publisher || 'غير محدد';
      byPublisher[pub] = (byPublisher[pub] || 0) + 1;

      const copies = B.totalCopies(b);
      totalCopies += copies;
      const availFull = B.availableFullCopies(b);
      const out = copies - availFull;
      borrowedCopies += out;
      const status = B.bookStatus(b);
      if (status === B.STATUS_FULL) fullyBorrowed += 1;
      else if (status === B.STATUS_PARTIAL) partiallyBorrowed += 1;
      for (const name of B.currentBorrowers(b)) activeBorrowers.add(name);

      if (typeof b.price === 'number' && b.price > 0) {
        totalValue += b.price * copies;
        pricedCopies += copies;
        pricedTitles += 1;
        if (!topPriced || b.price > topPriced.price) topPriced = { id: b.id, title: b.title, price: b.price };
      }
      if (B.isMultiVolume(b)) multiVolumeTitles += 1;

      let filled = 0;
      for (const f of completenessFields) if ((b[f] || '').toString().trim()) filled += 1;
      if (filled === completenessFields.length) completeRecords += 1;

      for (const l of b.loans || []) {
        if (l.returnedAt) continue;
        if (B.isOverdue(l, DEFAULT_LOAN_DAYS, now)) overdueLoans += 1;
        else if (B.isDueSoon(l, 7, now)) dueSoonLoans += 1;
      }
    }

    const completeness = books.length ? Math.round((completeRecords / books.length) * 100) : 100;

    return {
      totalBooks: books.length,
      totalAuthors: new Set(books.map((b) => b.author).filter(Boolean)).size,
      totalPublishers: new Set(books.map((b) => b.publisher).filter(Boolean)).size,
      totalCategories: new Set(books.map((b) => b.category).filter(Boolean)).size,
      totalCopies,
      borrowedCopies,
      availableCopies: totalCopies - borrowedCopies,
      fullyBorrowed,
      partiallyBorrowed,
      activeBorrowers: activeBorrowers.size,
      totalValue: Math.round(totalValue * 100) / 100,
      pricedCopies,
      pricedTitles,
      overdueLoans,
      dueSoonLoans,
      multiVolumeTitles,
      completeness,
      completeRecords,
      topPriced,
      byCategory,
      byPublisher,
    };
  }

  exportJson(filePath) {
    fs.writeFileSync(filePath, JSON.stringify(this.db, null, 2), 'utf-8');
  }

  exportCsv(filePath) {
    const headers = [
      'العنوان', 'المؤلف', 'دار النشر', 'الرقم المرجعي', 'المجال',
      'السلسلة', 'الترتيب في السلسلة', 'الرف', 'الكلمات المفتاحية', 'جهة الاقتناء', 'حالة النسخة',
      'الطبعة', 'سنة النشر', 'عدد الأجزاء', 'السعر', 'إجمالي النسخ', 'نسخ معارة', 'نسخ متاحة',
      'الحالة', 'المستعيرون الحاليون', 'ملاحظات',
    ];
    const rows = this.db.books.map((b) => [
      b.title, b.author, b.publisher, b.referenceNumber, b.category,
      b.series || '', b.seriesOrder || '', b.shelf || '', (b.keywords || []).join(' | '), b.acquisition || '', b.condition || '',
      b.edition, b.publishYear, b.volumes || 1, (b.price ?? ''),
      B.totalCopies(b), B.borrowedCopies(b), B.availableCopies(b),
      B.bookStatus(b), B.currentBorrowers(b).join(' | '), b.notes,
    ]);
    const escape = (v) => {
      const s = (v === undefined || v === null) ? '' : String(v);
      return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
    };
    const lines = [headers, ...rows].map((r) => r.map(escape).join(','));
    // BOM so Excel opens Arabic UTF-8 correctly.
    fs.writeFileSync(filePath, '\uFEFF' + lines.join('\r\n'), 'utf-8');
  }

  exportSelectedCsv(filePath, ids) {
    const wanted = new Set(Array.isArray(ids) ? ids : []);
    const books = this.db.books.filter((b) => wanted.has(b.id));
    const headers = ['العنوان', 'المؤلف', 'دار النشر', 'الرقم المرجعي', 'المجال', 'الرف', 'سنة النشر', 'عدد الأجزاء', 'إجمالي النسخ', 'نسخ متاحة', 'الحالة'];
    const rows = books.map((b) => [b.title, b.author, b.publisher, b.referenceNumber, b.category, b.shelf || '', b.publishYear, b.volumes || 1, B.totalCopies(b), B.availableCopies(b), B.bookStatus(b)]);
    const escape = (v) => {
      const text = v == null ? '' : String(v);
      return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
    };
    fs.writeFileSync(filePath, '\uFEFF' + [headers, ...rows].map((r) => r.map(escape).join(',')).join('\r\n'), 'utf8');
    return { count: books.length };
  }

  exportTxt(filePath) {
    const lines = this.db.books.map((b, i) => {
      const open = B.activeLoans(b).map((l) =>
        `      - ${l.borrowerName} [${B.loanScopeLabel(l)}] (منذ ${B.loanDurationDays(l)} يوماً)`);
      return [
        `${i + 1}. ${b.title || 'بدون عنوان'}`,
        `   المؤلف: ${b.author || '—'}`,
        `   دار النشر: ${b.publisher || '—'}`,
        `   المجال/التصنيف: ${b.category || '—'}`,
        `   الرقم المرجعي: ${b.referenceNumber || '—'}`,
        `   الطبعة: ${b.edition || '—'}    سنة النشر: ${b.publishYear || '—'}`,
        `   عدد الأجزاء: ${b.volumes || 1}${typeof b.price === 'number' ? `    السعر: ${b.price}` : ''}`,
        `   النسخ: ${B.totalCopies(b)} (متاح: ${B.availableCopies(b)}، معار: ${B.borrowedCopies(b)})`,
        `   الحالة: ${B.bookStatus(b)}`,
        open.length ? '   الإعارات المفتوحة:' : null,
        ...(open.length ? open : []),
        b.notes ? `   ملاحظات: ${b.notes}` : null,
        '',
      ].filter((l) => l !== null).join('\n');
    });
    const header = `فهرس مكتبة رَفّ\nتاريخ التصدير: ${new Date().toLocaleDateString('ar-EG')}\nإجمالي الكتب: ${this.db.books.length}\n${'='.repeat(40)}\n\n`;
    fs.writeFileSync(filePath, header + lines.join('\n'), 'utf-8');
  }

  buildPrintableHtml() {
    const rows = this.db.books.map((b, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${escapeXml(b.title)}</td>
        <td>${escapeXml(b.author)}</td>
        <td>${escapeXml(b.publisher)}</td>
        <td>${escapeXml(b.category)}</td>
        <td class="ltr">${escapeXml(b.referenceNumber)}</td>
        <td>${B.availableCopies(b)} / ${B.totalCopies(b)}</td>
        <td>${B.bookStatus(b)}</td>
      </tr>`).join('');

    return `<!DOCTYPE html>
<html lang="ar" dir="rtl"><head><meta charset="UTF-8">
<style>
  body { font-family: 'Segoe UI', Tahoma, Arial, sans-serif; padding: 24px; color: #23150a; }
  h1 { font-size: 20px; margin-bottom: 2px; }
  .sub { color: #6b5644; font-size: 12px; margin-bottom: 18px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th, td { border: 1px solid #ddc9a3; padding: 6px 8px; text-align: right; }
  th { background: #f5eddb; }
  .ltr { direction: ltr; text-align: left; font-family: monospace; }
</style></head>
<body>
  <h1>فهرس مكتبة رَفّ</h1>
  <div class="sub">تاريخ التصدير: ${new Date().toLocaleDateString('ar-EG')} — إجمالي الكتب: ${this.db.books.length}</div>
  <table>
    <thead><tr><th>#</th><th>العنوان</th><th>المؤلف</th><th>دار النشر</th><th>المجال</th><th>الرقم المرجعي</th><th>متاح / الكل</th><th>الحالة</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</body></html>`;
  }

  _validateIncomingDatabase(parsed) {
    if (!parsed || typeof parsed !== 'object' || !Array.isArray(parsed.books)) throw new Error('صيغة النسخة الكاملة غير صالحة');
    const incomingSchema = Number(parsed.schemaVersion) || 1;
    if (incomingSchema > SCHEMA_VERSION) throw new Error('هذه النسخة صادرة من إصدار أحدث من البرنامج ولا يمكن استعادتها بأمان');
    return {
      ...emptyDb(),
      ...parsed,
      books: parsed.books,
      trash: Array.isArray(parsed.trash) ? parsed.trash : [],
      activity: Array.isArray(parsed.activity) ? parsed.activity : [],
      settings: { ...defaultSettings(), ...(parsed.settings || {}) },
    };
  }

  mergeJson(filePath) {
    const raw = fs.readFileSync(filePath, 'utf-8');
    const parsed = JSON.parse(raw);
    const incoming = Array.isArray(parsed) ? parsed : parsed.books;
    if (!Array.isArray(incoming)) throw new Error('صيغة الملف غير صالحة');
    let backup = null;
    try { backup = this.createBackup('before-merge'); } catch (_) {}

    let added = 0;
    let skipped = 0;
    const skippedDetails = [];
    for (const item of incoming) {
      const normalizedIncoming = this._normalizeReference(item.referenceNumber || '');
      const incomingKey = this._referenceIdentity(normalizedIncoming);
      if (incomingKey && this._refIdentityIndex.has(incomingKey)) {
        skipped += 1;
        skippedDetails.push({ title: item.title || '', referenceNumber: item.referenceNumber || '', reason: 'رقم مرجعي مكرر' });
        continue;
      }
      const record = this.addBook({ ...item, referenceNumber: normalizedIncoming }, { keepReferenceNumber: true, defer: true });
      if (record && record.ok === false) {
        skipped += 1;
        skippedDetails.push({ title: item.title || '', referenceNumber: item.referenceNumber || '', reason: record.error });
        continue;
      }
      added += 1;
    }
    this._logActivity('library-merged', `دُمج ${added} كتاب وتُجاهل ${skipped} مكرر`, { added, skipped });
    this._save();
    return { added, skipped, skippedDetails, backup };
  }

  importJson(filePath) { return this.mergeJson(filePath); }

  restoreJson(filePath) {
    const parsed = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    const next = this._validateIncomingDatabase(parsed);
    const backup = this.createBackup('before-full-restore');
    this.db = next;
    this.db.schemaVersion = Math.min(Number(this.db.schemaVersion) || 1, SCHEMA_VERSION);
    this._migrate();
    this._rebuildIndexes();
    this._logActivity('library-restored', `استُعيدت نسخة كاملة تضم ${this.db.books.length} كتاباً`, { source: path.basename(filePath) });
    this._save();
    return { books: this.db.books.length, backup };
  }

  restoreBackupFile(filePath) { return this.restoreJson(filePath); }

  resetAll() {
    // Never destroy everything without a recoverable snapshot first.
    let backup = null;
    try { backup = this.createBackup('before-reset'); } catch (_) { /* ignore */ }
    const settings = this.getSettings();
    this.db = emptyDb();
    this.db.settings = settings;
    this._rebuildIndexes();
    this._logActivity('library-reset', 'حُذفت جميع بيانات المكتبة بعد إنشاء نسخة أمان');
    this._save();
    return { backup };
  }

  /**
   * Scans the library for problems worth flagging: overdue loans, incomplete
   * inventory records, and likely-duplicate titles. Read-only.
   */
  integrityCheck() {
    const books = Array.isArray(this.db.books) ? this.db.books : [];
    const now = Date.now();

    // 1) Operational alerts. These matter to the librarian but are not data
    // corruption, so they are reported separately from structural problems.
    const overdue = [];
    for (const b of books) {
      for (const l of Array.isArray(b.loans) ? b.loans : []) {
        if (!l.returnedAt && B.isOverdue(l, DEFAULT_LOAN_DAYS, now)) {
          overdue.push({
            bookId: b.id,
            title: b.title,
            referenceNumber: b.referenceNumber,
            borrower: l.borrowerName,
            days: B.loanDurationDays(l, now),
          });
        }
      }
    }

    // 2) Reference uniqueness. The map key is the complete normalized identity.
    // It never compares only a numeric suffix, so raf-0001 != raf-1001.
    const refMap = new Map();
    const referenceNormalization = [];
    const invalidReferences = [];
    for (const b of books) {
      const raw = (b.referenceNumber ?? '').toString();
      if (!raw.trim()) continue;
      const identity = this._referenceIdentity(raw);
      if (!identity) continue;
      if (!refMap.has(identity)) refMap.set(identity, []);
      refMap.get(identity).push(b);

      const normalized = this._normalizeReference(raw);
      if (normalized !== raw) {
        referenceNormalization.push({
          bookId: b.id,
          title: b.title || '(بدون عنوان)',
          before: raw,
          after: normalized,
        });
      }
      if (cleanReferenceText(raw).length > 100) {
        invalidReferences.push({ bookId: b.id, title: b.title || '(بدون عنوان)', referenceNumber: raw, reason: 'يتجاوز 100 حرف' });
      }
    }

    const duplicateRefs = [];
    for (const [identity, arr] of refMap) {
      if (arr.length < 2) continue;
      const refs = [...new Set(arr.map((b) => (b.referenceNumber || '').toString()))];
      duplicateRefs.push({
        identity,
        ref: this._normalizeReference(arr[0].referenceNumber),
        count: arr.length,
        references: refs,
        books: arr.map((b) => ({ bookId: b.id, title: b.title || '(بدون عنوان)', referenceNumber: b.referenceNumber || '' })),
        titles: arr.map((b) => b.title || '(بدون عنوان)'),
        formattingVariant: refs.length > 1,
      });
    }

    // 3) Duplicate/missing internal IDs. IDs are not shown to the user, but a
    // collision can make edit/delete actions target the wrong record.
    const idMap = new Map();
    const missingIds = [];
    for (const b of books) {
      const id = (b.id || '').toString().trim();
      if (!id) {
        missingIds.push({ title: b.title || '(بدون عنوان)', referenceNumber: b.referenceNumber || '' });
        continue;
      }
      if (!idMap.has(id)) idMap.set(id, []);
      idMap.get(id).push(b);
    }
    const duplicateIds = [];
    for (const [id, arr] of idMap) {
      if (arr.length > 1) duplicateIds.push({ id, count: arr.length, titles: arr.map((b) => b.title || '(بدون عنوان)') });
    }

    // 4) Missing essential bibliographic fields.
    const missing = [];
    for (const b of books) {
      const gaps = [];
      if (!(b.title || '').toString().trim()) gaps.push('العنوان');
      if (!(b.author || '').toString().trim()) gaps.push('المؤلف');
      if (!(b.referenceNumber || '').toString().trim()) gaps.push('الرقم المرجعي');
      if (!(b.category || '').toString().trim()) gaps.push('المجال');
      if (gaps.length) missing.push({ bookId: b.id, title: b.title || '(بدون عنوان)', referenceNumber: b.referenceNumber || '', gaps });
    }

    // 5) Inventory and loan-ledger consistency.
    const inventoryIssues = [];
    const loanIssues = [];
    const seenLoanIds = new Set();
    for (const b of books) {
      const title = b.title || '(بدون عنوان)';
      const copies = Number(b.copiesTotal);
      const volumes = Number(b.volumes);
      if (!Number.isInteger(copies) || copies < 1) {
        inventoryIssues.push({ bookId: b.id, title, field: 'عدد النسخ', value: b.copiesTotal, repairable: true });
      }
      if (!Number.isInteger(volumes) || volumes < 1) {
        inventoryIssues.push({ bookId: b.id, title, field: 'عدد الأجزاء', value: b.volumes, repairable: true });
      }
      if (!Array.isArray(b.loans)) {
        loanIssues.push({ bookId: b.id, title, issue: 'سجل الإعارات ليس قائمة صالحة', repairable: true });
        continue;
      }

      let highestLoanVolume = 0;
      for (const l of b.loans) {
        const lid = (l && l.id || '').toString().trim();
        if (!lid) loanIssues.push({ bookId: b.id, title, issue: 'إعارة بلا معرّف داخلي', repairable: true });
        else if (seenLoanIds.has(lid)) loanIssues.push({ bookId: b.id, title, issue: `معرّف إعارة مكرر: ${lid}`, repairable: true });
        else seenLoanIds.add(lid);

        const rawVolumes = Array.isArray(l && l.volumes) ? l.volumes : (l && l.volume != null ? [l.volume] : []);
        for (const raw of rawVolumes) {
          const v = Math.floor(Number(raw));
          if (Number.isFinite(v) && v > highestLoanVolume) highestLoanVolume = v;
        }
        if (!l || isNaN(Date.parse(l.borrowedAt))) {
          loanIssues.push({ bookId: b.id, title, issue: 'تاريخ إعارة غير صالح', repairable: true });
        }
        if (!l || isNaN(Date.parse(l.dueAt))) {
          loanIssues.push({ bookId: b.id, title, issue: 'تاريخ استحقاق غير صالح', repairable: true });
        }
        if (l && l.returnedAt && isNaN(Date.parse(l.returnedAt))) {
          loanIssues.push({ bookId: b.id, title, issue: 'تاريخ إرجاع غير صالح', repairable: false });
        }
      }
      if (highestLoanVolume > Math.max(1, Math.floor(volumes) || 1)) {
        inventoryIssues.push({
          bookId: b.id,
          title,
          field: 'عدد الأجزاء أقل من جزء مسجل في إعارة',
          value: highestLoanVolume,
          repairable: true,
        });
      }

      // The ledger must never say that more copies of one volume are out than
      // the title owns. This is flagged for review instead of deleting loans.
      const safeVolumes = Math.max(1, Math.floor(volumes) || 1, highestLoanVolume);
      const safeCopies = Math.max(1, Math.floor(copies) || 1);
      for (let v = 1; v <= safeVolumes; v++) {
        const out = B.borrowedOfVolume({ ...b, copiesTotal: safeCopies, volumes: safeVolumes }, v);
        if (out > safeCopies) {
          loanIssues.push({ bookId: b.id, title, issue: `الجزء ${v}: ${out} إعارات مفتوحة مقابل ${safeCopies} نسخة`, repairable: false });
        }
      }
    }

    // 6) Potential duplicate catalogue records. This is intentionally only a
    // hint; matching title/author is not treated as corruption or auto-deleted.
    const titleMap = new Map();
    for (const b of books) {
      const titleKey = normalizeTextForDuplicateHint(b.title);
      const authorKey = normalizeTextForDuplicateHint(b.author);
      if (!titleKey) continue;
      const key = titleKey + '\u0000' + authorKey;
      if (!titleMap.has(key)) titleMap.set(key, []);
      titleMap.get(key).push(b);
    }
    const possibleDuplicates = [];
    for (const [, arr] of titleMap) {
      if (arr.length > 1) {
        possibleDuplicates.push({
          title: arr[0].title,
          author: arr[0].author,
          count: arr.length,
          books: arr.map((b) => ({ bookId: b.id, referenceNumber: b.referenceNumber || '' })),
        });
      }
    }

    const repairableCount =
      referenceNormalization.length +
      missing.filter((m) => m.gaps.includes('الرقم المرجعي')).length +
      duplicateRefs.reduce((sum, group) => sum + Math.max(0, group.count - 1), 0) +
      missingIds.length +
      duplicateIds.reduce((sum, group) => sum + Math.max(0, group.count - 1), 0) +
      inventoryIssues.filter((x) => x.repairable).length +
      loanIssues.filter((x) => x.repairable).length;

    const structuralIssueCount = duplicateRefs.length + invalidReferences.length + missingIds.length +
      duplicateIds.length + missing.length + inventoryIssues.length + loanIssues.length;

    return {
      totalBooks: books.length,
      overdue,
      duplicateRefs,
      referenceNormalization,
      invalidReferences,
      missingIds,
      duplicateIds,
      missing,
      inventoryIssues,
      loanIssues,
      possibleDuplicates,
      repairableCount,
      structuralIssueCount,
      warningCount: overdue.length + possibleDuplicates.length,
      healthy: structuralIssueCount === 0,
    };
  }

  /**
   * Applies only deterministic repairs and creates a full backup first. It never
   * deletes a book or an actual loan. Duplicate references keep the oldest
   * record unchanged and receive fresh canonical numbers on the other records.
   */
  repairIntegrity() {
    const before = this.integrityCheck();
    if (!before.repairableCount) return { changed: 0, backup: null, actions: [], before, after: before };

    const backup = this.createBackup('before-integrity-repair');
    const actions = [];
    let changed = 0;
    const touch = (book, action) => {
      book.updatedAt = nowIso();
      actions.push(action);
      changed += 1;
    };

    // Repair book IDs first so every later action can target one record safely.
    const seenBookIds = new Set();
    for (const b of this.db.books) {
      const old = (b.id || '').toString().trim();
      if (!old || seenBookIds.has(old)) {
        const next = genId();
        b.id = next;
        touch(b, { type: 'book-id', title: b.title || '(بدون عنوان)', before: old || '—', after: next });
      }
      seenBookIds.add(b.id);
    }

    // Reserve every canonical sequence currently present. Fresh replacements
    // are selected from the lowest truly-free sequence, not from any suffix.
    const usedSeqs = new Set();
    for (const b of this.db.books) {
      const seq = this._canonicalRefSeq(b.referenceNumber);
      if (seq !== null) usedSeqs.add(seq);
    }
    const nextFreeReference = () => {
      let seq = 1;
      while (usedSeqs.has(seq)) seq += 1;
      usedSeqs.add(seq);
      return 'raf-' + String(seq).padStart(4, '0');
    };

    const groups = new Map();
    const noReference = [];
    for (const b of this.db.books) {
      const key = this._referenceIdentity(b.referenceNumber);
      if (!key) { noReference.push(b); continue; }
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push(b);
    }

    const ageValue = (b) => {
      const parsed = Date.parse(b.createdAt || '');
      return Number.isFinite(parsed) ? parsed : Number.MAX_SAFE_INTEGER;
    };
    for (const arr of groups.values()) {
      arr.sort((a, b) => ageValue(a) - ageValue(b));
      const keeper = arr[0];
      const normalizedKeeper = this._normalizeReference(keeper.referenceNumber);
      if (normalizedKeeper && normalizedKeeper !== keeper.referenceNumber) {
        const old = keeper.referenceNumber;
        keeper.referenceNumber = normalizedKeeper;
        touch(keeper, { type: 'reference-normalized', bookId: keeper.id, title: keeper.title || '(بدون عنوان)', before: old, after: normalizedKeeper });
      }
      for (const duplicate of arr.slice(1)) {
        const old = duplicate.referenceNumber || '—';
        const next = nextFreeReference();
        duplicate.referenceNumber = next;
        touch(duplicate, { type: 'reference-duplicate', bookId: duplicate.id, title: duplicate.title || '(بدون عنوان)', before: old, after: next });
      }
    }
    for (const b of noReference) {
      const next = nextFreeReference();
      b.referenceNumber = next;
      touch(b, { type: 'reference-missing', bookId: b.id, title: b.title || '(بدون عنوان)', before: '—', after: next });
    }

    // Repair inventory primitives and loan metadata without deleting history.
    const seenLoanIds = new Set();
    const defaultLoanDays = Number(this.db.settings && this.db.settings.loanDurationDays) || DEFAULT_LOAN_DAYS;
    for (const b of this.db.books) {
      if (!Array.isArray(b.loans)) {
        const oldType = typeof b.loans;
        b.loans = [];
        touch(b, { type: 'loan-ledger', bookId: b.id, title: b.title || '(بدون عنوان)', before: oldType, after: 'قائمة فارغة صالحة' });
      }

      let highestLoanVolume = 1;
      for (const l of b.loans) {
        const oldLoanId = (l.id || '').toString().trim();
        if (!oldLoanId || seenLoanIds.has(oldLoanId)) {
          l.id = genLoanId();
          touch(b, { type: 'loan-id', bookId: b.id, title: b.title || '(بدون عنوان)', before: oldLoanId || '—', after: l.id });
        }
        seenLoanIds.add(l.id);

        const raw = Array.isArray(l.volumes) ? l.volumes : (l.volume != null ? [l.volume] : []);
        const volumes = [...new Set(raw.map((v) => Math.floor(Number(v))).filter((v) => Number.isFinite(v) && v > 0))].sort((a, c) => a - c);
        for (const v of volumes) highestLoanVolume = Math.max(highestLoanVolume, v);
        if (JSON.stringify(l.volumes || []) !== JSON.stringify(volumes)) {
          l.volumes = volumes;
          l.volume = volumes.length === 1 ? volumes[0] : null;
          l.type = volumes.length ? 'volume' : 'full';
          touch(b, { type: 'loan-volumes', bookId: b.id, title: b.title || '(بدون عنوان)', before: 'غير منظم', after: volumes.join('، ') || 'نسخة كاملة' });
        }
        if (!l.volumeReturns || typeof l.volumeReturns !== 'object' || Array.isArray(l.volumeReturns)) {
          l.volumeReturns = {};
          touch(b, { type: 'volume-returns', bookId: b.id, title: b.title || '(بدون عنوان)', before: 'غير صالح', after: 'سجل صالح' });
        }
        if (isNaN(Date.parse(l.borrowedAt))) {
          const base = !isNaN(Date.parse(b.createdAt)) ? b.createdAt : nowIso();
          const old = l.borrowedAt || '—';
          l.borrowedAt = base;
          touch(b, { type: 'borrowed-at', bookId: b.id, title: b.title || '(بدون عنوان)', before: old, after: base });
        }
        if (isNaN(Date.parse(l.dueAt))) {
          const start = Date.parse(l.borrowedAt) || Date.now();
          const old = l.dueAt || '—';
          l.dueAt = new Date(start + defaultLoanDays * 86400000).toISOString();
          touch(b, { type: 'due-at', bookId: b.id, title: b.title || '(بدون عنوان)', before: old, after: l.dueAt });
        }
      }

      const oldVolumes = b.volumes;
      const normalizedVolumes = Math.max(1, Math.floor(Number(b.volumes)) || 1, highestLoanVolume);
      if (b.volumes !== normalizedVolumes) {
        b.volumes = normalizedVolumes;
        touch(b, { type: 'volumes', bookId: b.id, title: b.title || '(بدون عنوان)', before: oldVolumes, after: normalizedVolumes });
      }

      let busiest = 0;
      for (let v = 1; v <= normalizedVolumes; v++) busiest = Math.max(busiest, B.borrowedOfVolume(b, v));
      const oldCopies = b.copiesTotal;
      const normalizedCopies = Math.max(1, Math.floor(Number(b.copiesTotal)) || 1, busiest);
      if (b.copiesTotal !== normalizedCopies) {
        b.copiesTotal = normalizedCopies;
        touch(b, { type: 'copies', bookId: b.id, title: b.title || '(بدون عنوان)', before: oldCopies, after: normalizedCopies });
      }

      const cleanKeywords = sanitizeKeywords(b.keywords);
      if (JSON.stringify(cleanKeywords) !== JSON.stringify(b.keywords || [])) {
        b.keywords = cleanKeywords;
        touch(b, { type: 'keywords', bookId: b.id, title: b.title || '(بدون عنوان)', before: 'غير منظم', after: cleanKeywords.join('، ') });
      }
      const cleanCondition = sanitizeCondition(b.condition);
      if (b.condition !== cleanCondition) {
        const old = b.condition;
        b.condition = cleanCondition;
        touch(b, { type: 'condition', bookId: b.id, title: b.title || '(بدون عنوان)', before: old || '—', after: cleanCondition });
      }
    }

    this.db.nextRefSeq = (() => {
      let seq = 1;
      const used = this._usedCanonicalSeqs();
      while (used.has(seq)) seq += 1;
      return seq;
    })();

    if (changed) {
      this._rebuildIndexes();
      this._logActivity('integrity-repaired', `أُصلحت ${changed} مشكلة في سلامة البيانات`, { changed });
      this._save();
    }
    const after = this.integrityCheck();
    return { changed, backup, actions, before, after };
  }

  /** Exports only currently-overdue loans as a CSV. */
  exportOverdueCsv(filePath) {
    const now = Date.now();
    const headers = ['العنوان', 'الرقم المرجعي', 'المستعير', 'وسيلة التواصل', 'النطاق', 'تاريخ الإعارة', 'تاريخ الاستحقاق', 'أيام التأخير', 'ملاحظة'];
    const rows = [];
    for (const b of this.db.books) {
      for (const l of b.loans || []) {
        if (l.returnedAt || !B.isOverdue(l, DEFAULT_LOAN_DAYS, now)) continue;
        const overdueDays = l.dueAt ? Math.max(0, Math.ceil((now - Date.parse(l.dueAt)) / 86400000)) : B.loanDurationDays(l, now);
        rows.push([
          b.title, b.referenceNumber, l.borrowerName, l.contact || '',
          B.loanScopeLabel(l),
          l.borrowedAt ? new Date(l.borrowedAt).toLocaleDateString('ar-EG') : '',
          l.dueAt ? new Date(l.dueAt).toLocaleDateString('ar-EG') : '',
          overdueDays, l.note || '',
        ]);
      }
    }
    const escape = (v) => {
      const s = (v === undefined || v === null) ? '' : String(v);
      return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
    };
    const lines = [headers, ...rows].map((r) => r.map(escape).join(','));
    fs.writeFileSync(filePath, '\uFEFF' + lines.join('\r\n'), 'utf-8');
    return { count: rows.length };
  }

  /**
   * Returns every currently-open loan flattened with its book and borrower
   * details, sorted with overdue loans first (then by how late they are).
   * Used by the loans view and the borrower PDF exports.
   */
  /**
   * Recomputes the due date of every currently-open loan as borrowedAt + days.
   * Used when the librarian chooses to apply a new loan period retroactively.
   * Returns how many loans were updated.
   */
  applyLoanDurationToOpenLoans(days) {
    const d = Math.max(1, Math.min(3650, Math.floor(Number(days) || 30)));
    let updated = 0;
    for (const b of this.db.books) {
      let touched = false;
      for (const l of b.loans || []) {
        if (l.returnedAt) continue;
        const start = Date.parse(l.borrowedAt) || Date.now();
        l.dueAt = new Date(start + d * 86400000).toISOString();
        updated += 1; touched = true;
      }
      if (touched) b.updatedAt = nowIso();
    }
    if (updated) { this._logActivity('loan-dates-updated', `حُدّثت مواعيد ${updated} إعارة`, { updated, days: d }); this._save(); }
    return { updated };
  }

  getLoanCenter() {
    const now = Date.now();
    const out = [];
    for (const b of this.db.books) {
      for (const l of b.loans || []) {
        const active = B.isLoanActive(l, b);
        const dueTime = Date.parse(l.dueAt);
        const overdue = active && B.isOverdue(l, DEFAULT_LOAN_DAYS, now);
        const dueToday = active && Number.isFinite(dueTime) && new Date(dueTime).toDateString() === new Date(now).toDateString();
        const dueSoon = active && !overdue && !dueToday && B.isDueSoon(l, 7, now);
        const returnedParts = B.returnedLoanVolumes(l, b);
        const outstandingParts = B.outstandingLoanVolumes(l, b);
        out.push({
          loanId: l.id,
          bookId: b.id,
          title: b.title,
          referenceNumber: b.referenceNumber,
          borrowerName: l.borrowerName || '',
          contact: l.contact || '',
          note: l.note || '',
          scope: B.loanScopeLabel(l),
          outstandingScope: B.outstandingScopeLabel(l, b),
          borrowedAt: l.borrowedAt || null,
          dueAt: l.dueAt || null,
          returnedAt: l.returnedAt || null,
          active,
          overdue,
          dueToday,
          dueSoon,
          overdueDays: overdue && Number.isFinite(dueTime) ? Math.max(0, Math.ceil((now - dueTime) / 86400000)) : 0,
          partialReturn: active && returnedParts.length > 0 && outstandingParts.length > 0,
          returnedParts,
          outstandingParts,
        });
      }
    }
    out.sort((a, b) => {
      if (a.active !== b.active) return a.active ? -1 : 1;
      if (a.overdue !== b.overdue) return a.overdue ? -1 : 1;
      if (a.overdue && b.overdue) return b.overdueDays - a.overdueDays;
      if (a.active && b.active) return (Date.parse(a.dueAt) || Infinity) - (Date.parse(b.dueAt) || Infinity);
      return (Date.parse(b.returnedAt) || 0) - (Date.parse(a.returnedAt) || 0);
    });
    return out;
  }

  getBorrowersDirectory() {
    const map = new Map();
    for (const b of this.db.books) for (const l of b.loans || []) {
      const name = (l.borrowerName || '').trim();
      if (!name) continue;
      const key = normalizeTextForDuplicateHint(name);
      if (!map.has(key)) map.set(key, { name, contacts: new Map(), loans: [], currentCount: 0, overdueCount: 0, lastLoanAt: null });
      const profile = map.get(key);
      const contact = (l.contact || '').trim();
      if (contact) profile.contacts.set(contact, (profile.contacts.get(contact) || 0) + 1);
      const active = B.isLoanActive(l, b);
      const overdue = active && B.isOverdue(l, DEFAULT_LOAN_DAYS);
      if (active) profile.currentCount += 1;
      if (overdue) profile.overdueCount += 1;
      if (!profile.lastLoanAt || Date.parse(l.borrowedAt) > Date.parse(profile.lastLoanAt)) profile.lastLoanAt = l.borrowedAt;
      profile.loans.push({ bookId: b.id, title: b.title, referenceNumber: b.referenceNumber, loanId: l.id, borrowedAt: l.borrowedAt, dueAt: l.dueAt, returnedAt: l.returnedAt, active, overdue, scope: B.outstandingScopeLabel(l, b) });
    }
    return [...map.values()].map((p) => {
      const sortedContacts = [...p.contacts.entries()].sort((a, b) => b[1] - a[1]);
      return { ...p, contact: sortedContacts[0]?.[0] || '', contacts: sortedContacts.map(([value]) => value), totalLoans: p.loans.length, contactsMap: undefined };
    }).sort((a, b) => b.currentCount - a.currentCount || b.totalLoans - a.totalLoans || a.name.localeCompare(b.name, 'ar'));
  }

  getPublicBooks() {
    return this.db.books.filter((b) => !b.archivedAt).map((b) => ({
      ...b,
      acquisition: '',
      notes: '',
      loans: (b.loans || []).map((l) => ({
        id: l.id,
        type: l.type,
        volume: l.volume,
        volumes: Array.isArray(l.volumes) ? l.volumes : [],
        volumeReturns: l.volumeReturns || {},
        returnedAt: l.returnedAt || null,
        borrowedAt: l.borrowedAt || null,
        dueAt: l.dueAt || null,
        borrowerName: '',
        contact: '',
        note: '',
      })),
    }));
  }

  getPublicMeta() {
    const meta = this.getMeta();
    return { ...meta, borrowers: [], borrowerProfiles: [], filePath: '' };
  }

  getPublicSettings() {
    const s = this.getSettings();
    return { institutionName: s.institutionName, logo: s.logo, scannerGapMs: s.scannerGapMs, scannerTerminator: s.scannerTerminator };
  }

  getActiveLoans({ overdueOnly = false } = {}) {
    const now = Date.now();
    const out = [];
    for (const b of this.db.books) {
      for (const l of b.loans || []) {
        if (l.returnedAt) continue;
        const overdue = B.isOverdue(l, DEFAULT_LOAN_DAYS, now);
        if (overdueOnly && !overdue) continue;
        const overdueDays = overdue && l.dueAt
          ? Math.max(0, Math.ceil((now - Date.parse(l.dueAt)) / 86400000)) : 0;
        out.push({
          bookId: b.id,
          title: b.title,
          referenceNumber: b.referenceNumber,
          borrowerName: l.borrowerName || '',
          contact: l.contact || '',
          scope: B.outstandingScopeLabel(l, b),
          borrowedAt: l.borrowedAt || null,
          dueAt: l.dueAt || null,
          overdue,
          overdueDays,
          note: l.note || '',
        });
      }
    }
    // Overdue first, then most-overdue, then soonest due.
    out.sort((a, b) => {
      if (a.overdue !== b.overdue) return a.overdue ? -1 : 1;
      if (a.overdue && b.overdue) return b.overdueDays - a.overdueDays;
      return (Date.parse(a.dueAt) || 0) - (Date.parse(b.dueAt) || 0);
    });
    return out;
  }
}

module.exports = Store;
